name: appoint
version: '0.1.0.0'
synopsis: TODO Initial project template from stack
description: Please see README.md
category: Acme
author: Rob Berry
maintainer: example@example.com
copyright: ! 'Copyright: (c) 2016 Rob Berry'
license: BSD3
github: rob-b/appoint
tested-with: GHC==7.10.2
extra-source-files:
- README.md
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Appoint.Lib
  - Appoint.Wrap
  dependencies:
  - base >=4.7 && <5
  - text
  - bytestring
  - github
  - vector
  - transformers
  - rainbow
executables:
  appoint:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - appoint
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - appoint
    - hspec
    - QuickCheck
    - text
